title:        Preguntale a tu Madre
tagline:      El programa de irreverencia social que nadie quiere que escuches.
baseurl:      ""
paginate:     20
locale:       "es-UY"

s3: "http://preguntaleatumadre.com.s3-website-us-west-2.amazonaws.com/"
# author:
#   name:       Author name
#   url:        http://yourhomepage.com

# sass:
#   style: compact # possible values: nested expanded compact compressed

# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
url: "http://www.preguntaleatumadre.com"
markdown: kramdown
plugins:
  - jekyll-paginate

timezone: America/Montevideo

collections:
  programas:
    output: true

exclude:
  - Makefile
  - CNAME
  - node_modules
  - webpack.config.js
  - package.json
  - package-lock.json
#   - Gemfile
#   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
