title:        Preguntale a tu Madre
tagline:      "Donde no existen preguntas estúpidas…"
baseurl:      ""
locale:       "es-UY"


pagination:
  enabled: true
  per_page: 20
  permalink: '/pagina:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

permalink: programas/:year/:month/:day/:title:output_ext

s3: "http://preguntaleatumadre.com.s3-website-us-west-2.amazonaws.com/"
# author:
#   name:       Author name
#   url:        http://yourhomepage.com

sass:
  style: compressed # expanded compressed

# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
url: "https://www.preguntaleatumadre.com"
markdown: kramdown
plugins:
  - jekyll-paginate-v2

timezone: America/Montevideo

# collections:
#   programas:
#     output: true

exclude:
  - Makefile
  - CNAME
  - node_modules/
  - webpack.config.js
  - package.json
  - package-lock.json
  - scripts/
#   - Gemfile
#   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
